import type { KeyContext } from '@/theory/keys';

export interface Bar {
  chords: { symbol: string; beats: number }[];
}

export interface Song {
  id: string;
  title: string;
  /** Genre/era description, never a real artist's song. */
  styleRef: string;
  key: KeyContext;
  bpm: number;
  timeSig: [number, number];
  sections: { name: string; bars: number }[];
  /** Roman numeral per bar (flattened over sections) — makes transposition free. */
  romanized: string[];
  /** Earliest stage it appears in. */
  stage: number;
}

export const SONGS: Song[] = [
  {
    id: 'first-light',
    title: 'First Light',
    styleRef: 'Warm four-chord pop, the kind that opens a festival set',
    key: { tonic: 'C', mode: 'major' },
    bpm: 72,
    timeSig: [4, 4],
    sections: [
      { name: 'Verse', bars: 8 },
      { name: 'Chorus', bars: 8 },
    ],
    romanized: [
      // Verse: home and back, twice
      'I',
      'V',
      'vi',
      'IV',
      'I',
      'V',
      'vi',
      'IV',
      // Chorus: the 50s turn
      'I',
      'vi',
      'IV',
      'V',
      'I',
      'vi',
      'IV',
      'V',
    ],
    stage: 1,
  },
  {
    id: 'northline',
    title: 'Northline',
    styleRef: 'Slow-burn piano ballad with a climbing middle',
    key: { tonic: 'G', mode: 'major' },
    bpm: 66,
    timeSig: [4, 4],
    sections: [
      { name: 'Verse', bars: 8 },
      { name: 'Lift', bars: 4 },
    ],
    romanized: ['I', 'iii', 'IV', 'V', 'I', 'iii', 'IV', 'V', 'vi', 'IV', 'I', 'V'],
    stage: 3,
  },
  {
    id: 'paper-sun',
    title: 'Paper Sun',
    styleRef: 'Breezy soul-pop with a turnaround',
    key: { tonic: 'F', mode: 'major' },
    bpm: 84,
    timeSig: [4, 4],
    sections: [{ name: 'Groove', bars: 8 }],
    romanized: ['I', 'vi', 'ii', 'V', 'I', 'vi', 'ii', 'V'],
    stage: 3,
  },
  {
    id: 'ember',
    title: 'Ember',
    styleRef: 'Minor-key indie folk, slow build, brushed drums',
    key: { tonic: 'A', mode: 'minor' },
    bpm: 76,
    timeSig: [4, 4],
    sections: [
      { name: 'Verse', bars: 8 },
      { name: 'Chorus', bars: 8 },
    ],
    romanized: [
      // Verse: the minor anthem loop, twice
      'i',
      'VI',
      'III',
      'VII',
      'i',
      'VI',
      'III',
      'VII',
      // Chorus: leans on the minor three-chord cell, then lifts to VI
      'i',
      'iv',
      'v',
      'i',
      'i',
      'iv',
      'VI',
      'V',
    ],
    stage: 5,
  },
  {
    id: 'round-the-circle',
    title: 'Round the Circle',
    styleRef: 'Standards-era practice etude; walks ii-V-I down in fourths',
    key: { tonic: 'C', mode: 'major' },
    bpm: 66,
    timeSig: [4, 4],
    sections: [{ name: 'Etude', bars: 12 }],
    // Four ii-V-I cells (C, F, B♭, E♭) written against C so transposing the
    // whole etude stays one edit.
    romanized: [
      'ii7',
      'V7',
      'Imaj7',
      'v7',
      'I7',
      'IVmaj7',
      'i7',
      'IV7',
      'bVIImaj7',
      'iv7',
      'bVII7',
      'bIIImaj7',
    ],
    stage: 5,
  },
  {
    id: 'slow-tide',
    title: 'Slow Tide',
    styleRef: 'Standards-era ballad, AABA, brushes and a lot of space',
    key: { tonic: 'Eb', mode: 'major' },
    bpm: 60,
    timeSig: [4, 4],
    sections: [
      { name: 'A', bars: 8 },
      { name: 'A2', bars: 8 },
      { name: 'B (bridge)', bars: 8 },
      { name: 'A3', bars: 8 },
    ],
    romanized: [
      // A: home, out to the subdominant, back through ii-V
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'IVmaj7',
      'ii7',
      'V7',
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'IVmaj7',
      'Imaj7',
      'Imaj7',
      // B: lifts to IV and walks back down
      'IVmaj7',
      'IVmaj7',
      'iii7',
      'vi7',
      'ii7',
      'ii7',
      'V7',
      'V7',
      // A3
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'IVmaj7',
      'Imaj7',
      'Imaj7',
    ],
    stage: 6,
  },
  {
    id: 'brass-district',
    title: 'Brass District',
    styleRef: 'Horn-section soul; verse, pre-chorus, chorus',
    key: { tonic: 'Bb', mode: 'major' },
    bpm: 96,
    timeSig: [4, 4],
    sections: [
      { name: 'Verse', bars: 8 },
      { name: 'Pre-chorus', bars: 4 },
      { name: 'Chorus', bars: 8 },
    ],
    romanized: [
      'I7',
      'I7',
      'IV7',
      'IV7',
      'I7',
      'I7',
      'ii7',
      'V7',
      'IV',
      'V',
      'iii',
      'vi',
      'I',
      'V',
      'vi',
      'IV',
      'I',
      'V',
      'IV',
      'IV',
    ],
    stage: 6,
  },
  {
    id: 'nightbus',
    title: 'Nightbus',
    styleRef: 'Late-night minor AABA, electric piano and rain',
    key: { tonic: 'D', mode: 'minor' },
    bpm: 88,
    timeSig: [4, 4],
    sections: [
      { name: 'A', bars: 8 },
      { name: 'A2', bars: 8 },
      { name: 'B (bridge)', bars: 8 },
      { name: 'A3', bars: 8 },
    ],
    romanized: [
      'i',
      'VI',
      'III',
      'VII',
      'i',
      'VI',
      'iv',
      'V',
      'i',
      'VI',
      'III',
      'VII',
      'i',
      'iv',
      'i',
      'i',
      'III',
      'VII',
      'VI',
      'V',
      'III',
      'VII',
      'iv',
      'V',
      'i',
      'VI',
      'III',
      'VII',
      'i',
      'iv',
      'i',
      'i',
    ],
    stage: 6,
  },
  {
    id: 'cassette-summer',
    title: 'Cassette Summer',
    styleRef: 'Bright guitar-pop with a lifting pre-chorus',
    key: { tonic: 'A', mode: 'major' },
    bpm: 104,
    timeSig: [4, 4],
    sections: [
      { name: 'Verse', bars: 8 },
      { name: 'Pre-chorus', bars: 4 },
      { name: 'Chorus', bars: 8 },
    ],
    romanized: [
      'I',
      'V',
      'vi',
      'IV',
      'I',
      'V',
      'IV',
      'IV',
      'vi',
      'IV',
      'I',
      'V',
      'I',
      'IV',
      'vi',
      'V',
      'I',
      'IV',
      'V',
      'I',
    ],
    stage: 6,
  },
  {
    id: 'blue-monday-blues',
    title: 'Blue Monday Blues',
    styleRef: 'Twelve-bar blues, shuffle feel, dominant sevenths throughout',
    key: { tonic: 'C', mode: 'major' },
    bpm: 88,
    timeSig: [4, 4],
    sections: [{ name: 'Chorus (12 bars)', bars: 12 }],
    romanized: ['I7', 'IV7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'I7', 'V7', 'IV7', 'I7', 'V7'],
    stage: 7,
  },
  {
    id: 'red-clay-road',
    title: 'Red Clay Road',
    styleRef: 'Blues-rock shuffle with a quick change',
    key: { tonic: 'G', mode: 'major' },
    bpm: 100,
    timeSig: [4, 4],
    sections: [{ name: 'Chorus (12 bars)', bars: 12 }],
    // Quick change: bar 2 goes to IV before returning.
    romanized: ['I7', 'IV7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'V7', 'IV7', 'IV7', 'I7', 'V7'],
    stage: 7,
  },
  {
    id: 'the-long-way-home',
    title: 'The Long Way Home',
    styleRef: 'Jazz-standard AABA; ii-V-I in three keys before it lands',
    key: { tonic: 'F', mode: 'major' },
    bpm: 72,
    timeSig: [4, 4],
    sections: [
      { name: 'A', bars: 8 },
      { name: 'A2', bars: 8 },
      { name: 'B (bridge)', bars: 8 },
      { name: 'A3', bars: 8 },
    ],
    romanized: [
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'iii7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'ii7',
      'V7',
      'Imaj7',
      // Bridge modulates by fourths and walks back
      'i7',
      'IV7',
      'bVIImaj7',
      'bVIImaj7',
      'v7',
      'I7',
      'IVmaj7',
      'V7',
      'Imaj7',
      'vi7',
      'ii7',
      'V7',
      'Imaj7',
      'IVmaj7',
      'Imaj7',
      'Imaj7',
    ],
    stage: 7,
  },
];

export function getSong(id: string): Song | undefined {
  return SONGS.find((s) => s.id === id);
}
